export const testimonials = [
  {
    name: "Mi-Rae",
    image: "assets/images/iv_profile_picture_01.png",
    role: "Frontend Developer Intern",
    rating: 4.5,
    text: "Pelayanannya cepat dan ramah, pesanan gas langsung diantar ke rumah!",
  },
  {
    name: "Mi-ji",
    image: "assets/images/iv_profile_picture_02.png",
    role: "UI/UX Designer Enthusiast",
    rating: 5,
    text: "Air minumnya selalu segar dan higienis, cocok buat kebutuhan harian keluarga.",
  },
  {
    name: "Ayase",
    image: "assets/images/iv_profile_picture_03.png",
    role: "Software Engineering Student",
    rating: 5,
    text: "Toko bersih, penataan rapi, dan stafnya sangat membantu. Mantap!",
  },
  {
    name: "Mitsuka",
    image: "assets/images/iv_profile_picture_04.png",
    role: "Fullstack Developer Wannabe",
    rating: 4,
    text: "Langganan gas di sini karena selalu ready stock dan harga bersahabat.",
  },
  {
    name: "Hu-So",
    image: "assets/images/iv_profile_picture_05.png",
    role: "IT Support Specialist",
    rating: 5,
    text: "Suka banget sama layanan antar galonnya, gak perlu repot keluar rumah.",
  },
  {
    name: "Marnie",
    image: "assets/images/iv_profile_picture_06.png",
    role: "Data Analyst Enthusiast",
    rating: 5,
    text: "Respons WA-nya cepat, pengiriman juga gak pakai nunggu lama. Terpercaya!",
  },
  {
    name: "Jin-Woo",
    image: "assets/images/iv_profile_picture_07.png",
    role: "Machine Learning Student",
    rating: 4,
    text: "Sangat terbantu dengan layanan Toko Sulthon, respon cepat dan tepat waktu!",
  },
  {
    name: "Eun-Na",
    image: "assets/images/iv_profile_picture_08.png",
    role: "Cloud Computing Enthusiast",
    rating: 5,
    text: "Gas dan airnya selalu tersedia dan dikirim tepat waktu. Terima kasih Sulthon Shop!",
  },
  {
    name: "So-Min",
    image: "assets/images/iv_profile_picture_09.png",
    role: "Cybersecurity Hobbyist",
    rating: 5,
    text: "Kualitas airnya bagus dan tidak bau, cocok untuk kebutuhan harian kami sekeluarga.",
  },
  {
    name: "Ryu-Ta",
    image: "assets/images/iv_profile_picture_10.png",
    role: "Mobile App Developer",
    rating: 5,
    text: "Rekomendasi dari teman, ternyata benar-benar memuaskan pelayanannya!",
  },
  {
    name: "Cha-Rin",
    image: "assets/images/iv_profile_picture_11.png",
    role: "Backend Developer Intern",
    rating: 5,
    text: "Adminnya fast response, dan pengantarannya juga ramah. Good service!",
  },
  {
    name: "Han-Bi",
    image: "assets/images/iv_profile_picture_12.png",
    role: "Tech Content Creator",
    rating: 5,
    text: "Udah langganan lama, gak pernah kecewa sama pelayanan dan produknya.",
  },
];
